In [1]:
# revise the order of the faces in feature_matrix. 
# make it the same as rating_matrix: MIT, Glas, faceothers, genhead

import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np


feature_arr = pd.read_csv('feature_matrix.csv')

In [2]:
feature_arr.head()

,Unnamed: 0,dataset,img_num,nose_width,nose_length,lip_thickness,face_length,eye_height,eye_width,face_width_prom,...,brow_to_hair,fWHR,face_shape,heartshapeness,nose_shape,lip_fullness,eye_shape,eye_size,upper_head_len,midface_len
0,0,mit,0,39.012818,69.000000,21.524938,269.007435,14.258772,37.067467,204.022058,...,70.586826,1.751246,0.758425,1.236293,0.565403,0.080016,0.384671,0.053005,0.349749,0.355243
1,1,mit,1,38.052595,75.059976,30.000000,279.016129,14.792855,41.157973,202.299283,...,77.772103,1.585187,0.725045,1.246838,0.506963,0.107521,0.359417,0.053018,0.387671,0.353154
2,2,mit,2,37.013511,77.006493,24.035669,280.000000,13.152946,35.850451,201.009950,...,78.000000,1.582706,0.717893,1.182227,0.480654,0.085842,0.366884,0.046975,0.382143,0.360548
3,3,mit,3,40.012498,76.006579,31.019202,292.083892,14.538690,41.157973,212.115535,...,85.501462,1.650392,0.726214,1.218733,0.526435,0.106200,0.353241,0.049776,0.414279,0.326676
4,4,mit,4,35.014283,75.006666,26.022681,274.016423,15.282760,40.155922,199.022612,...,67.516665,1.468792,0.726316,1.220975,0.466816,0.094968,0.380585,0.055773,0.379609,0.371377

In [23]:
n1 = np.arange(0, 100)
n2 = np.arange(150, 200)
n3 = np.arange(100, 150)
new_order = np.hstack((n1,n2,n3))
new_feature_arr = feature_arr.reindex(new_order)

In [13]:
new_feature_arr.head()

,Unnamed: 0,dataset,img_num,nose_width,nose_length,lip_thickness,face_length,eye_height,eye_width,face_width_prom,...,brow_to_hair,fWHR,face_shape,heartshapeness,nose_shape,lip_fullness,eye_shape,eye_size,upper_head_len,midface_len
0,0,mit,0,39.012818,69.000000,21.524938,269.007435,14.258772,37.067467,204.022058,...,70.586826,1.751246,0.758425,1.236293,0.565403,0.080016,0.384671,0.053005,0.349749,0.355243
1,1,mit,1,38.052595,75.059976,30.000000,279.016129,14.792855,41.157973,202.299283,...,77.772103,1.585187,0.725045,1.246838,0.506963,0.107521,0.359417,0.053018,0.387671,0.353154
2,2,mit,2,37.013511,77.006493,24.035669,280.000000,13.152946,35.850451,201.009950,...,78.000000,1.582706,0.717893,1.182227,0.480654,0.085842,0.366884,0.046975,0.382143,0.360548
3,3,mit,3,40.012498,76.006579,31.019202,292.083892,14.538690,41.157973,212.115535,...,85.501462,1.650392,0.726214,1.218733,0.526435,0.106200,0.353241,0.049776,0.414279,0.326676
4,4,mit,4,35.014283,75.006666,26.022681,274.016423,15.282760,40.155922,199.022612,...,67.516665,1.468792,0.726316,1.220975,0.466816,0.094968,0.380585,0.055773,0.379609,0.371377

In [24]:
del new_feature_arr['Unnamed: 0']
del new_feature_arr['dataset']
del new_feature_arr['img_num']

In [25]:
new_feature_arr.to_csv('new_feature_matrix.csv')